<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="MediatorParse"
     targetNamespace="http://xmlns.oracle.com/VRUMigration/VRUMIgrationCheck/MediatorParse"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/VRUMigration/VRUMIgrationCheck/MediatorParse"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="MediatorParse.MediatorParse">
        <plnk:role name="callback_ptt" portType="tns:callback_ptt"/>
        <plnk:role name="execute_ptt" portType="tns:execute_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/VRUMigration/VRUMIgrationCheck/MediatorParse"
         location="MediatorParse.wsdl"/>
</wsdl:definitions>
