<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://oagj.webservices"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:soapenc12="http://www.w3.org/2003/05/soap-encoding"
                xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/"
                xmlns:soapenc11="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:soap12="http://www.w3.org/2003/05/soap-envelope" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/MediatorParse.wsdl"/>
        <oracle-xsl-mapper:rootElement name="VRUParseMigrationData" namespace="http://oagj.webservices"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/VRUParsemigrationData.wsdl"/>
        <oracle-xsl-mapper:rootElement name="VRUParseMigrationData" namespace="http://oagj.webservices"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU FEB 05 14:49:43 CET 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:VRUParseMigrationData>
      <ns0:VRUParseMigrationDataRequest>
        <ns0:ctx>
          <ns0:clientId>
            <xsl:value-of select="/ns0:VRUParseMigrationData/ns0:VRUParseMigrationDataRequest/ns0:ctx/ns0:clientId"/>
          </ns0:clientId>
          <ns0:username>
            <xsl:value-of select="/ns0:VRUParseMigrationData/ns0:VRUParseMigrationDataRequest/ns0:ctx/ns0:username"/>
          </ns0:username>
          <xsl:if test="/ns0:VRUParseMigrationData/ns0:VRUParseMigrationDataRequest/ns0:ctx/ns0:password">
            <ns0:password>
              <xsl:value-of select="/ns0:VRUParseMigrationData/ns0:VRUParseMigrationDataRequest/ns0:ctx/ns0:password"/>
            </ns0:password>
          </xsl:if>
          <xsl:if test="/ns0:VRUParseMigrationData/ns0:VRUParseMigrationDataRequest/ns0:ctx/ns0:transactionId">
            <ns0:transactionId>
              <xsl:value-of select="/ns0:VRUParseMigrationData/ns0:VRUParseMigrationDataRequest/ns0:ctx/ns0:transactionId"/>
            </ns0:transactionId>
          </xsl:if>
        </ns0:ctx>
        <ns0:requestId>
          <xsl:value-of select="/ns0:VRUParseMigrationData/ns0:VRUParseMigrationDataRequest/ns0:requestId"/>
        </ns0:requestId>
      </ns0:VRUParseMigrationDataRequest>
    </ns0:VRUParseMigrationData>
  </xsl:template>
</xsl:stylesheet>
