<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://oagj.webservices"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:soapenc12="http://www.w3.org/2003/05/soap-encoding"
                xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/"
                xmlns:soapenc11="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:soap12="http://www.w3.org/2003/05/soap-envelope"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/mockVRUPreCheckMigrationDataRemoteHttpBinding.wsdl"/>
        <oracle-xsl-mapper:rootElement name="VRUPreCheckMigrationDataResponse" namespace="http://oagj.webservices"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/MediatorPreCheck.wsdl"/>
        <oracle-xsl-mapper:rootElement name="VRUPreCheckMigrationDataResponse" namespace="http://oagj.webservices"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU FEB 05 11:35:55 CET 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:VRUPreCheckMigrationDataResponse>
      <ns0:VRUPreCheckMigrationDataResp>
        <xsl:if test="/ns0:VRUPreCheckMigrationDataResponse/ns0:VRUPreCheckMigrationDataResp/ns0:responseWithMessage">
          <ns0:responseWithMessage>
            <ns0:resultCode>
              <xsl:value-of select="/ns0:VRUPreCheckMigrationDataResponse/ns0:VRUPreCheckMigrationDataResp/ns0:responseWithMessage/ns0:resultCode"/>
            </ns0:resultCode>
            <ns0:resultDescription>
              <xsl:value-of select="/ns0:VRUPreCheckMigrationDataResponse/ns0:VRUPreCheckMigrationDataResp/ns0:responseWithMessage/ns0:resultDescription"/>
            </ns0:resultDescription>
            <xsl:for-each select="/ns0:VRUPreCheckMigrationDataResponse/ns0:VRUPreCheckMigrationDataResp/ns0:responseWithMessage/ns0:messageWithParams">
              <ns0:messageWithParams>
                <xsl:if test="@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <ns0:messageCode>
                  <xsl:value-of select="ns0:messageCode"/>
                </ns0:messageCode>
                <ns0:messageDescription>
                  <xsl:value-of select="ns0:messageDescription"/>
                </ns0:messageDescription>
                <ns0:severity>
                  <xsl:value-of select="ns0:severity"/>
                </ns0:severity>
                <xsl:for-each select="ns0:parameters">
                  <ns0:parameters>
                    <xsl:if test="@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <ns0:parName>
                      <xsl:value-of select="ns0:parName"/>
                    </ns0:parName>
                    <ns0:parValue>
                      <xsl:value-of select="ns0:parValue"/>
                    </ns0:parValue>
                  </ns0:parameters>
                </xsl:for-each>
              </ns0:messageWithParams>
            </xsl:for-each>
          </ns0:responseWithMessage>
        </xsl:if>
      </ns0:VRUPreCheckMigrationDataResp>
    </ns0:VRUPreCheckMigrationDataResponse>
  </xsl:template>
</xsl:stylesheet>
